-- Migration : table products (catalogue de pieges testes, lies a l'affiliation Amazon)
-- A importer apres schema.sql via phpMyAdmin.

CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(150) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    brand VARCHAR(100) DEFAULT NULL,
    asin VARCHAR(20) DEFAULT NULL,
    amazon_url VARCHAR(500) DEFAULT NULL,
    technology ENUM('uv','co2','propane','aspirant','solaire','larvaire','combine') DEFAULT 'combine',
    surface_m2 INT UNSIGNED DEFAULT NULL,
    noise_db DECIMAL(4,1) DEFAULT NULL,
    autonomy_hours INT UNSIGNED DEFAULT NULL,
    price_eur DECIMAL(7,2) DEFAULT NULL,
    rating DECIMAL(3,1) DEFAULT NULL COMMENT 'Note sur 10',
    rank_global TINYINT UNSIGNED DEFAULT NULL COMMENT 'Position dans le top du moment',
    badge VARCHAR(60) DEFAULT NULL COMMENT 'ex: Meilleur global, Rapport qualite-prix',
    target_use VARCHAR(50) DEFAULT NULL COMMENT 'terrasse, chambre, pro, jardin, tigre',
    verdict VARCHAR(255) DEFAULT NULL COMMENT 'Phrase verdict courte',
    pitch TEXT DEFAULT NULL COMMENT 'Description longue 2-3 paragraphes',
    pros JSON DEFAULT NULL,
    cons JSON DEFAULT NULL,
    hero_svg MEDIUMTEXT DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    status ENUM('draft','published','archived') DEFAULT 'published',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_rank (status, rank_global),
    INDEX idx_target_use (target_use),
    INDEX idx_technology (technology)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================================
-- Seed : 6 produits phares (le top du moment, mai 2026)
-- Les ASIN sont des PLACEHOLDERS a remplacer par les vrais une fois Amazon Partenaires valide
-- ===========================================================

INSERT INTO products (slug, name, brand, asin, technology, surface_m2, noise_db, autonomy_hours, price_eur, rating, rank_global, badge, target_use, verdict, pitch, pros, cons) VALUES

('mosquito-magnet-patriot',
 'Mosquito Magnet Patriot',
 'Mosquito Magnet',
 'B07PXXXXXX',
 'co2', 4000, 28.5, 504, 499.00, 9.4, 1,
 'Meilleur global',
 'jardin',
 'Le souverain. Cher, mais plebiscite par les utilisateurs sur grand jardin.',
 'Le standard de l''industrie depuis 15 ans. Bruleur catalytique propane, octenol et CO2. Surface annoncee jusqu''a 4000 m2. Les utilisateurs remontent une efficacite particulierement marquee sur le moustique tigre apres 2-3 semaines de fonctionnement continu.',
 JSON_ARRAY('Surface annoncee tres grande', 'Plebiscite contre Aedes albopictus dans les retours', 'Robuste sur la duree selon les acheteurs', 'SAV reactif'),
 JSON_ARRAY('Investissement initial eleve', '80-150 EUR/an de propane et octenol', 'Volumineux a stocker l''hiver')),

('biogents-bg-mosquitaire',
 'Biogents BG-Mosquitaire',
 'Biogents',
 'B00FXXXXXX',
 'aspirant', 200, 35.0, 0, 229.00, 9.1, 2,
 'Rapport qualite-prix',
 'jardin',
 'L''allemand serieux. Le compromis prix/efficacite plebiscite dans les retours.',
 'Piege aspirant qui imite les emanations corporelles humaines. Branche sur secteur, pas de propane. Recharge BG-Sweetscent a remplacer tous les 2 mois. Les utilisateurs remontent une efficacite reguliere contre le moustique tigre, ideal jardin urbain ou periurbain.',
 JSON_ARRAY('Pas de propane a gerer', '35 dB constructeur, peu audible selon les retours', 'Apprecie contre le tigre', 'Conception solide selon les acheteurs'),
 JSON_ARRAY('Cable secteur a tirer dans le jardin', 'Surface annoncee limitee a 200 m2', 'Recharge mensuelle ~12 EUR')),

('inadays-uv-led-silent',
 'Inadays UV LED Silent',
 'Inadays',
 'B09XXXXXXX',
 'uv', 50, 22.0, 8, 59.00, 8.2, 3,
 'Meilleur petit budget',
 'chambre',
 'Le silencieux d''interieur. 22 dB annonces, confirmes par les retours.',
 'Petit piege UV avec ventilateur aspirant. Pas de grille electrique grezillante. 22 dB constructeurs, le consensus utilisateurs confirme un fonctionnement compatible chambre. Sur batterie 8h ou USB. Peu efficace en exterieur selon les retours.',
 JSON_ARRAY('Vraiment silencieux', 'USB-C, batterie integree', 'Compact et discret', 'Sous 60 EUR'),
 JSON_ARRAY('Inefficace contre le moustique tigre', 'Surface tres limitee (50 m2)', 'Surtout utile contre mouches/moucherons')),

('aspectek-bug-zapper',
 'Aspectek Bug Zapper 20W',
 'Aspectek',
 'B00BXXXXXX',
 'uv', 100, 48.0, 0, 49.90, 6.8, 4,
 'Petit budget exterieur',
 'terrasse',
 'Le grezilleur classique. Apprecie sur les volants generaux, peu efficace sur le tigre selon les retours.',
 'Lampe UV 20W avec grille electrique. Bruyant (grezillements 48 dB constructeur). Les retours utilisateurs convergent : efficace sur mouches, papillons de nuit, moucherons mais peu d''effet sur Aedes albopictus, qui n''est pas attire par l''UV selon les recherches entomologiques.',
 JSON_ARRAY('Tres bon prix', 'Robuste, etanche IP44', 'Couvre 100 m2 d''insectes volants'),
 JSON_ARRAY('Inefficace contre le moustique tigre', 'Bruyant (grezillements 48 dB)', 'Tue aussi des insectes utiles')),

('biogents-gat',
 'Biogents BG-GAT (piege a oeufs)',
 'Biogents',
 'B07YXXXXXX',
 'larvaire', 0, 0.0, 0, 39.90, 8.7, 5,
 'Anti-tigre longue duree',
 'tigre',
 'Le piege a ponte qui casse le cycle. A combiner avec un BG-Mosquitaire selon les retours.',
 'Imite une eau stagnante (lieu de ponte du tigre). Les femelles viennent pondre, restent piegees. Selon le constructeur et les retours utilisateurs, agit sur 4-6 semaines pour reduire la population locale. Pas de courant, pas de bruit.',
 JSON_ARRAY('Aucune electricite, aucun bruit', 'Specifique Aedes albopictus', 'Effet long terme (cycle de reproduction)', 'A combiner pour synergies'),
 JSON_ARRAY('Pas d''effet visible la 1re semaine', 'Couvre seulement 50 m2', 'A vider tous les 15 jours')),

('coleman-mosquito-deleto',
 'Coleman Mosquito Deleto',
 'Coleman',
 'B00HXXXXXX',
 'co2', 800, 32.0, 168, 199.00, 7.5, 6,
 'Compact et nomade',
 'terrasse',
 'L''alternative plus accessible au Mosquito Magnet, sur petite/moyenne terrasse.',
 'Brule un melange propane+octenol pour generer CO2 et chaleur. Surface annoncee 800 m2. Les retours utilisateurs pointent une construction moins solide que le Mosquito Magnet pour environ la moitie du prix. Bon compromis pour terrasse 50-100 m2.',
 JSON_ARRAY('Prix divise par 2 vs Mosquito Magnet', 'Mobile (poignee, batterie option)', 'Efficace sur tigre (CO2)'),
 JSON_ARRAY('Construction plus fragile', 'Cartouche octenol obligatoire', 'Recharges propane plus frequentes'));
